[theme]
# Base theme - "light" or "dark"
base = "dark"

primaryColor = "#FFB81C"

backgroundColor = "#0E1117"

secondaryBackgroundColor = "#1F2430"

textColor = "#FAFAFA"

font = "sans serif"

[server]
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true